# Generated by Django 5.0 on 2023-12-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('department', models.CharField(choices=[('Python', 'Python'), ('React', 'React'), ('Php', 'Php'), ('IOS', 'IOS'), ('Flutter', 'flutter')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=30)),
                ('emp_role', models.CharField(choices=[('Employee', 'Employee'), ('HR_Manager', 'HR_Manager'), ('Senior_Manager', 'Senior_Manager'), ('Manager', 'Manager'), ('Assistant_Manager', 'Assistant_Manager'), ('Project_Manager', 'Project_Manager'), ('Team_Leader', 'Team_Leader'), ('Software_Developer', 'Software_Developer'), ('Interns/Trainees', 'Interns/Trainees')], default='Employee', max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(choices=[('Python', 'Python'), ('React', 'React'), ('Php', 'Php'), ('IOS', 'IOS'), ('Flutter', 'flutter')], default='', max_length=200)),
                ('token', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Assign_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500)),
                ('assign_by', models.CharField(max_length=500)),
                ('department', models.CharField(choices=[('Python', 'Python'), ('React', 'React'), ('Php', 'Php'), ('IOS', 'IOS'), ('Flutter', 'flutter')], default='', max_length=100)),
                ('task_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=100)),
                ('task_assign_date', models.DateField()),
                ('task_finish_date', models.DateField()),
                ('task_status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('submitted', 'submitted')], default='in progress', max_length=100)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.project')),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.register_employee')),
            ],
        ),
    ]
